apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flask-test-app
  # You'll usually want to add your resources to the argocd namespace.
  namespace: argocd
  # Add this finalizer ONLY if you want these to cascade delete.
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # The project the application belongs to.
  project: default

  # Source of the application manifests
  source:
    repoURL: https://github.com/tanvinaxane/testingECR.git # Can point to either a Helm chart repo or a git repo.
    targetRevision: HEAD # For Helm, this refers to the chart version.
    path: flask-test-app # This has no meaning for Helm charts pulled directly from a Helm repo instead of git.

name: ArgoCD sync workflow
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Sync ArgoCD Application with Kubernetes
        uses: omegion/argocd-actions@v1
        with:
          address: "http://aad18b92a45fb46d5b54b38315c44f2a-2097128699.us-east-1.elb.amazonaws.com"
          token: ${{ secrets.ARGOCD_TOKEN }}
          action: sync
          appName: "flask-test-app"
