apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metronetpocargocd
  namespace: multinsfeature1
spec:
  project: default

  source:
    repoURL: https://github.com/tanvinaxane/testingECR.git
    targetRevision: HEAD
    path: "."
  destination:
    server: https://kubernetes.default.svc
    namespace: testnsargocd

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
