name: AUTO DELETION OF APPS ON MERGE

on:
  push: 
    branches: [demo] 

jobs:

  push:
    name: On push operation
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_TOKEN}} 
        aws-region: us-east-1
        
    - name: Setup EKS Kubectl
      uses: zachguo/setup-eks-kubectl@v1
      with:
        cluster: metronetpocmulticluster # name of your EKS cluster
        region: us-east-1 # region of your EKS cluster
        namespace: argocddemonew2 # optional namespace context, default value is 'default'
  
    - name: Connect to your cluster
      run: |
        aws eks --region us-east-1 update-kubeconfig --name metronetpocmulticluster
        kubectl delete app argocddemonew2
        
    - name: Install ArgoCD 
      uses: clowdhaus/argo-cd-action/@main
      with:
        version: 2.3.4
        command: version
        options: --client
        
    - name: ArgoCD App Deletion Info
      uses: actions/checkout@v2
    - name: Configuring Argo Details
      uses: butterfly1924/argocd-actions@master
      with:
          address: "http://a867a311ffe544ac885bb44c65c553b2-70831757.us-east-1.elb.amazonaws.com"
          token: ${{ secrets.ARGOCD_TOKEN }}
          insecure: "true"
          action: sync
          appName: "argocddemonew2"
          imageTag: "dev"
      
    #- name: Terminate App Post Merge
     # run: |
      #  argocd app delete argocddemonew2
       # echo "App deleted"
  #kubectl delete deployment mongoargocd --namespace=argocddemonew2
        
        
        
    
        
        
        
        
