name: AUTO DELETION OF PODS ON MERGE

on:
  push: 
    branches: [demo] 

jobs:

  push:
    name: On push operation
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_TOKEN}} 
        aws-region: us-east-1
        
    - name: Install kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'v1.21.3'
      id: install
  
    - name: Install ArgoCD 
      uses: clowdhaus/argo-cd-action/@main
      with:
        version: 2.3.4
        command: version
        options: --client
          
    - name: Sync ArgoCD App
      uses: inarix/ga-argocd-action@v1
      with:
        argocdToken: argocd --insecure app sync ${{ secrets.ARGOCD_TOKEN }}
        argocdEndpoint: "http://a867a311ffe544ac885bb44c65c553b2-70831757.us-east-1.elb.amazonaws.com"
        #insecure: ${{ false }}
        applicationNamespace: "argocddemonew2"
        destClusterName: ${{secrets.CLUSTER_NAME}}
        applicationName: "argocddemonew2"
        actionName: "delete"
        applicationParams: "image.debug=true;replicaCount=0;nodeSelector.name=multiclusternode"
      
    - name: Terminate pods post merge
      run: |
        argocd app delete argocddemonew2
        echo "App deleted."
  #kubectl delete deployment mongoargocd --namespace=argocddemonew2
        
        
        
    
        
        
        
        
